# Generated by Django 3.0.2 on 2021-03-28 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('description', models.CharField(max_length=500, verbose_name='Déscription')),
                ('direction', models.CharField(max_length=120, verbose_name='Adresse')),
                ('telephone', models.IntegerField()),
                ('url1', models.CharField(max_length=2085)),
                ('url2', models.CharField(max_length=2085)),
                ('url3', models.CharField(max_length=2085)),
                ('url4', models.CharField(max_length=2085)),
                ('x', models.FloatField(verbose_name='longitude')),
                ('y', models.FloatField(verbose_name='latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('COFFEE', 'Coffee'), ('DINNER', 'Dinner')], max_length=20)),
                ('thumbnail', models.ImageField(default='recipe_thumbnails/default.png', upload_to='recipe_thumbnails')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('recipe', models.ManyToManyField(to='api.Recipe')),
            ],
        ),
    ]
